### ISSUE TITLE
Open failed: assert 0 <= colx < X12_MAX_COLS

### ISSUE THREAD

**Issue by tonal** [python-excel/xlrd#127] opened 2015-01-26 07:15 UTC
```
$ wget http://www.wilo-russia.ru/price/PriceWilo2014.xlsx
$ python -c 'import xlrd; xlrd.open_workbook("PriceWilo2014.xlsx")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "xlrd/__init__.py", line 416, in open_workbook
    ragged_rows=ragged_rows,
  File "xlrd/xlsx.py", line 791, in open_workbook_2007_xml
    x12sheet.process_stream(zflo, heading)
  File "xlrd/xlsx.py", line 531, in own_process_stream
    self.do_dimension(elem)
  File "xlrd/xlsx.py", line 565, in do_dimension
    rowx, colx = cell_name_to_rowx_colx(last_cell_ref)
  File "xlrd/xlsx.py", line 89, in cell_name_to_rowx_colx
    assert 0 <= colx < X12_MAX_COLS
AssertionError
```

**Comment by tonal** [comment] 2015-01-26 08:09
OpenOffice 4.3 open this file.

Also Ok open openpyxl http://openpyxl.readthedocs.org:
```$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from openpyxl import load_workbook
>>> wb = load_workbook("PriceWilo2014.xlsx")
>>> ws = wb.worksheets[0]
>>> print ws.max_row, ws.max_column
10901 1025
```

**Comment by martinmaillard** [comment] 2015-01-28 09:50
Same here after modifying an Excel document in LibreOffice.

**Comment by jmcnamara** [comment] 2015-02-10 10:38
This issue is that the dimensions in the file don't include a column range:

```xml
 <dimension ref="1:10901"/>
```
This would usually be something like:

```xml
 <dimension ref="A1:K10901"/>
```

I looked at the `dimension` definition in ECMA-376 but I can't determine if this is valid or not.

Even if it is valid it is hard to see how it can be parsed in a meaningful way.

**Comment by perimosocordiae** [comment] 2015-03-10 19:06
I just ran across this error, and the message it displays isn't very user-friendly. Would it be possible to insert a check somewhere for this kind of malformed dimension attribute, which reports something more google-able?

**Comment by tonal** [comment] 2015-04-06 05:10
Also see bag #56 and pull request #107

**Comment by tonal** [comment] 2015-04-06 05:16
Pull request #107 work Ok for my test file.

**Comment by cjw296** [comment] 2016-06-03 05:23
Dupe of #56

**Closed by cjw296** 2016-06-03 05:23 UTC
