### ISSUE TITLE
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 510-511: illegal encoding

### ISSUE THREAD

**Issue by fewspider** [python-excel/xlrd#126] opened 2015-01-15 11:22 UTC
when I use `xlrd.open_workbook(file_name)` ，it doesnot work.
The error traceback is like that:

* * *
File "run_task.py", line 46, in check_init_data
    xlsx_result = XlsxReader().read_xlsx(path)
  File "/home/fewspider/workspace/python/hmt_erp/task/importing_task/xlsx_read.py", line 116, in read_xlsx
    bk = xlrd.open_workbook(file_name)
  File "/home/fewspider/workspace/python/hmt_erp/venv/lib/python2.7/site-packages/xlrd/__init__.py", line 435, in open_workbook
    ragged_rows=ragged_rows,
  File "/home/fewspider/workspace/python/hmt_erp/venv/lib/python2.7/site-packages/xlrd/book.py", line 116, in open_workbook_xls
    bk.parse_globals()
  File "/home/fewspider/workspace/python/hmt_erp/venv/lib/python2.7/site-packages/xlrd/book.py", line 1158, in parse_globals
    self.handle_sst(data)
  File "/home/fewspider/workspace/python/hmt_erp/venv/lib/python2.7/site-packages/xlrd/book.py", line 1129, in handle_sst
    self._sharedstrings, rt_runlist = unpack_SST_table(strlist, uniquestrings)
  File "/home/fewspider/workspace/python/hmt_erp/venv/lib/python2.7/site-packages/xlrd/book.py", line 1372, in unpack_SST_table
    accstrg += unicode(rawstrg, "utf_16_le")
  File "/home/fewspider/workspace/python/hmt_erp/venv/lib64/python2.7/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
* * *

**Comment by jpatel3** [comment] 2015-01-23 16:20
Is it one of the file or any file?

Can you share the file too if the data is not that confidential?

**Comment by fewspider** [comment] 2015-01-24 05:36
@jpatel3 just like just this file,I can use LibreOffice open it,but xlrd donesnot work.https://www.dropbox.com/s/bwu6erd5mzo5e9s/a-2-2.xls?dl=0

**Comment by sjmachin** [comment] 2015-01-26 01:55
Diagnosis:
Cells L747-L752 have rubbish at the end.
747: \x02 (meaningless C0 control character)
748: \x01 (meaningless C0 control character)
749: \udee0\x97\udeb8\x97 (the \udenn are isolated low-surrogates, \x97 is a meaningless C1 control character)
750: 10 occurrences of \uffff ("guaranteed not to be a Unicode character at all")
751 and 752: \x11 (meaningless C0 control character)
The exception is raised by the utf_16_le codec complaining about the \udee0 surrogate in L749.

More to follow ...

**Comment by nickcash** [comment] 2015-07-06 16:50
@fewspider one workaround is to monkey-patch the unicode() call in unpack_SST_table to allow sloppy unicode:

`xlrd.book.unpack_SST_table.func_globals["unicode"] = lambda s, e: unicode(s, e, errors="ignore")`

I've recently encountered a similar situation, where a spreadsheet created by a 3rd-party program fails to open in xlrd, but opens okay in Excel and LibreOffice (Excel actually quietly fixes the spreadsheet when its opened, which is insane but irrelevant), in my case I had to monkey-patch `xlrd.biffh.unpack_unicode`. 

I'm wondering if it would be worthwhile to add a book-level option to set different unicode error handlers (strict/ignore/replace)?

**Comment by cckim** [comment] 2015-08-19 18:11
A similar problem (on the surface doesn't sound exactly the same based on Diagnosis above) can be reproduced with:
<pre>
from xlwt import Workbook
from xlrd import open_workbook
x = u"abv\ud835\uddf9\ud835\uddfb" # abv[an EMOTI l] [an EMOTI n]
workbook = Workbook(encoding='utf-8')
worksheet = workbook.add_sheet('checking emotis')
worksheet.write(1,1,4100*'a'+x)
workbook.save("/tmp/Hello")
wb = open_workbook("/tmp/Hello")
</pre>
From what I can tell xlwt is leaving a surrogate pair dangling across data buckets and xlrd when pulling it at 'accstrg += unicode(rawstrg, "utf_16_le")' fails as it only sees the first part.      Suspect the 'correct' fix might be to delay the conversion to accstrg until the entire raw string has been accumulated?  Various lessor solutions might also be effective (e.g. accumulate rawstrg only on error / hacked this and it worked)

Note: the resulting xls is readable using libreoffice.   Have seen this issue from time to time and it has been rare; as it  should be as the sequencing of operations must be just right to get the surrogate to split across the datatab buckets.

**Comment by cjw296** [comment] 2016-06-02 23:45
I'm afraid this bug seems to be a couple of cases of xlrd not reading what are basically invalid Excel files.
Barring anyone coming forward to do what will probably be a huge amount of work to support this in any meaningful way, I'm afraid I'm going to close this with a "sorry, please fix the bugs in the source".

**Closed by cjw296** 2016-06-02 23:45 UTC

**Comment by ltvlx** [comment] 2018-04-24 08:13
Had the same problem but the "broken" Excel file was created by xlwt.
Re-saving file from MS Excel (even without any modifications) solved the problem.

**Comment by rcoder29** [comment] 2018-09-19 21:50
Ran into similar problem, working with legacy .xls files from some of our vendors
After lot of playing around and reading some of the forums, following monkey patching seem to do the job!

xlrd.biffh.unicode=lambda s, e: s.decode(e, errors="ignore")
xlrd.book.unicode=lambda s, e: s.decode(e, errors="ignore")

**Comment by windleafy** [comment] 2019-04-19 07:57
Thx
It's great
xlrd.biffh.unicode=lambda s, e: s.decode(e, errors="ignore")
xlrd.book.unicode=lambda s, e: s.decode(e, errors="ignore")
