### ISSUE TITLE
PendingDeprecationWarning with Python 2.7.10

### ISSUE THREAD

**Issue by dwt** [python-excel/xlrd#315] opened 2018-12-17 18:25 UTC
Though I suspect that this warning will also surface with python3 the same way.

The problem is that [xlsx:59](https://github.com/python-excel/xlrd/blob/master/xlrd/xlsx.py#L59) checks if etree has `.iter()` support. However, this check does not always work, especially not for `defusedxml.cElementTree` on python2 which is the first alternative it tries.

Looking at past bugs, #104 seems to have dealt with that same problem by defining a wrapper function. Though this wrapper function has later been removed sometime after 2014.

Not sure what the best course of action here is. The wrapper function is probably a more correct solution than what is there now, but there was probably a reason to go from the exception based design to the bool. 

If the problem was speed, then maybe something like this can be tried?

```
def tree_iterator(tree):
  global tree_iterator
    if hasattr(tree, 'iter'):
      tree_iterator = lambda x: x.iter()
    else:
      tree_iterator = lambda x: x.getiterator()
    return tree_iterator(tree)
```

What do you think?

**Comment by dwt** [comment] 2019-01-08 08:47
Ping? Any maintainer around here?

**Comment by dwt** [comment] 2019-01-08 13:59
For reference, I'm seeing this error with etree (from the stdlib) too.

```
ERROR: redacted.test.name
  mate -w +181 somewhere/some_test.py  # test_something
    result = pd.read_excel(io, sheet_name='Questions')
  mate -w +178 virtualenv/site-packages/pandas/util/_decorators.py  # wrapper
    return func(*args, **kwargs)
  mate -w +178 virtualenv/site-packages/pandas/util/_decorators.py  # wrapper
    return func(*args, **kwargs)
  mate -w +307 virtualenv/site-packages/pandas/io/excel.py  # read_excel
    io = ExcelFile(io, engine=engine)
  mate -w +392 virtualenv/site-packages/pandas/io/excel.py  # __init__
    self.book = xlrd.open_workbook(file_contents=data)
  mate -w +138 virtualenv/site-packages/xlrd/__init__.py  # open_workbook
    ragged_rows=ragged_rows,
  mate -w +812 virtualenv/site-packages/xlrd/xlsx.py  # open_workbook_2007_xml
    x12book.process_stream(zflo, 'Workbook')
  mate -w +266 virtualenv/site-packages/xlrd/xlsx.py  # process_stream
    for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():
  mate -w +681 python_install/python2.7/xml/etree/ElementTree.py  # getiterator
    PendingDeprecationWarning, stacklevel=2
PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
```

**Comment by dwt** [comment] 2019-01-08 14:06
After further investigation I'm quite confused. https://github.com/python-excel/xlrd/blob/master/xlrd/xlsx.py#L59 on my machine imports and uses defusedxml.cElementTree to test and find out that it does not support iter, while later on in actual usage the PendingDeprecationWarning is thrown from python2.7/xml/etree/ElementTree.py. Does that make any sense to you?

**Comment by asteppke** [comment] 2019-01-09 12:38
Using pytest and xlrd I get similar warnings for python 3.6 as well. So this does not seem to be limited to python 2.7.10. 

pytest example output using a current xlrd 1.2.0:

    [...]
    C:\Users\user\AppData\Local\Continuum\Anaconda3\lib\site-packages\xlrd\xlsx.py:266: 
    PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 
    'list(tree.iter())' instead.
    for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():
    C:\Users\user\AppData\Local\Continuum\Anaconda3\lib\site-packages\xlrd\xlsx.py:312: 
    PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 
    'list(tree.iter())' instead.

**Comment by dwt** [comment] 2019-01-14 08:15
@maintainer: Ping? Are you still present?

**Comment by dwt** [comment] 2019-01-22 06:55
@jdufresne Hi! Is this project still alive? Is there sense in preparing a pull request? It is widely used - so if you don't have the time, stating clearly on the front page that you are searching a new maintainer might help!

**Comment by joelgenter** [comment] 2019-03-18 20:06
I can confirm that this issue is showing up in python 3.7 as well:

```bash
  /anaconda3/envs/myenv/lib/python3.7/site-packages/xlrd/xlsx.py:266: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
    for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():

  /anaconda3/envs/myenv/lib/python3.7/site-packages/xlrd/xlsx.py:312: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
    for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():
```

**Comment by irony-iron** [comment] 2019-03-19 14:46
Element_has_iter should be marked as global in that places:
/anaconda3/envs/myenv/lib/python3.7/site-packages/xlrd/xlsx.py:312
/anaconda3/envs/myenv/lib/python3.7/site-packages/xlrd/xlsx.py:266
but it is local variable

**Comment by inclucive-dev1** [comment] 2019-03-20 04:35
@dwt I'm seeing this as well. Thanks for reporting this. I'm not related to this project, but will be very interested in forking a separate development if there is enough interest in this. I will also be forking the defusedxml project, and any other related projects, if there is a need to keep apace of current interest in the "Python-UNO" bridge in general.

**Comment by inclucive-dev1** [comment] 2019-03-20 04:48
> Element_has_iter should be marked as global in that places:
> /anaconda3/envs/myenv/lib/python3.7/site-packages/xlrd/xlsx.py:312
> /anaconda3/envs/myenv/lib/python3.7/site-packages/xlrd/xlsx.py:266
> currently it is local variable and always Null

@irony-iron I just checked. It's global. Which version are you using?

**Comment by irony-iron** [comment] 2019-03-20 06:18
@inclucive-dev1 python 3.6
I made PullRequest to illustrate how should be https://github.com/python-excel/xlrd/pull/327/files

**Comment by inclucive-dev1** [comment] 2019-03-20 06:20
> @inclucive-dev1 python 3.6
> I made PullRequest to illustrate how should be https://github.com/python-excel/xlrd/pull/327/files

Did u try to check the value in that variable? Set it to something else manually. You'll see that those 2 lines of codes (266 and 312) actually does pull in the correct value. Perhaps I'm understanding this wrong, and it's proper Python convention to always declare a variable global *right before* using it?

**Comment by inclucive-dev1** [comment] 2019-03-20 06:35
@dwt @joelgenter @irony-iron  I've forked this and patched the problem. The new package name is `xlrdinc`. Really need your help in beating that package and reporting bugs and problems. We're using a lot of Python-UNO; Microsoft `.xls` really isn't going away anytime soon.

**Comment by inclucive-dev1** [comment] 2019-03-20 06:38
> After further investigation I'm quite confused. https://github.com/python-excel/xlrd/blob/master/xlrd/xlsx.py#L59 on my machine imports and uses defusedxml.cElementTree to test and find out that it does not support iter, while later on in actual usage the PendingDeprecationWarning is thrown from python2.7/xml/etree/ElementTree.py. Does that make any sense to you?

@dwt `defusedxml` extends the original class `etree.ElementTree`. It makes sense. What doesn't make sense is the indirect way the author used to test for an existing object attribute (aka class function, in this case). Might be due to some old Python limitation causing odd programming practices, we may never know by now. We just need to get things working.

**Comment by gh640** [comment] 2019-05-10 10:15
I met this warning when using this package with `defusedxml`.

PR:

- https://github.com/python-excel/xlrd/pull/335

I tested the code of this PR in my environment (Python 3.7) and it looks fine. I'd like someone to review the PR once it's passed the CI tests. Thanks :)

**Comment by WillAyd** [comment] 2019-05-18 23:44
> After further investigation I'm quite confused. https://github.com/python-excel/xlrd/blob/master/xlrd/xlsx.py#L59 on my machine imports and uses defusedxml.cElementTree to test and find out that it does not support iter, while later on in actual usage the PendingDeprecationWarning is thrown from python2.7/xml/etree/ElementTree.py. Does that make any sense to you?

@dwt I believe the reason for that is the import machinery and management of a global to determine whether or not `iter` gets called. defusedxml is prioritizes first in import:

https://github.com/python-excel/xlrd/blob/c5a95aedce43a5997e76e468e286d85ef035b173/xlrd/xlsx.py#L39

But fails the check that assigns to the global which determines whether or not iter gets used:

https://github.com/python-excel/xlrd/blob/c5a95aedce43a5997e76e468e286d85ef035b173/xlrd/xlsx.py#L59

So I think best solution would be to either change prioritization of import machinery or update assignment to global to properly account for defusedxml

**Comment by inclusive-dev1** [comment] 2019-05-19 13:18
> I met this warning when using this package with `defusedxml`.
> 
> PR:
> 
> * #335
> 
> I tested the code of this PR in my environment (Python 3.7) and it looks fine. I'd like someone to review the PR once it's passed the CI tests. Thanks :)

We can't merge that because we're not the maintainers. If you'll put your PR at [our package](https://github.com/inclusive-dev1/xlrdinc), we can merge it.

We'll set up our own Travis soon, including Coveralls. Docs probably need a good amount of rewrite by now, so we'll fix that last.

**Comment by inclusive-dev1** [comment] 2019-05-19 14:02
> So I think best solution would be to either change prioritization of import machinery or update assignment to global to properly account for defusedxml

@WillAyd Not sure I understand that fully. :-P

> I tested the code of this PR in my environment

@gh640 I think your fix is the most elegant fix. It acknowledges **in one place** the internal changes in `cElementTree`. Still, a more complete fix might just be to outright remove `.getiterator()` from all the codes.

Back to @WillAyd :

## Deprecated `.getiterator()`

I'd say we best not mess with the *import priorities*. *Still*, you're actually right about the import priorities because the current xlrd codes uses the deprecated `xml.etree.cElementTree`. It will be a rather wide-ranging rewrite if we want to remove the use of that deprecated package. (FYI, Python 3's `xml.etree.ElementTree` now claims to use a fast implementation, which deprecates the need to rely on a fast *C implementation* that is `xml.etree.cElementTree`.)

About the *global* you're referring to, it's not a problem with assigning the global wrong. The most likely reason for failure is that `defusedxml.cElementTree`'s internal structure has changed, possibly because `xml.etree.cElementTree` has changed! Maybe the deprecation has evolved to an outright removal of some functions in `xml.etree.cElementTree`?

## Moving away from the deprecated to the new `.iter()`

Note how [we fixed it](https://github.com/inclusive-dev1/xlrdinc/commit/007e2d278fdb5bfae78d47e347044ca0fe2e0987#diff-131808f84c2dbf8993a1b6e01ec39830) by simply using the `ElementTree` object returned, and finding the *new* method `.iter()` on it.

**Since we can test for `.iter()` on the returned object from `ET.parse()`, the complete fix could mean removing unneeded code further above (see @gh640 's PR).**

The [official Python docs](https://docs.python.org/2.7/library/xml.etree.elementtree.html#elementtree-objects) also mentions that `ElementTree.iter()` is the method to use, and that `xml.etree.ElementTree.parse()` [returns an `ElementTree`](https://docs.python.org/2.7/library/xml.etree.elementtree.html#functions) to test with.

So, we did a quick fix that simply aligns with the latest and greatest of Python 2 and 3.

# Likely that even `cElementTree` deprecated methods similarly

Our fix doesn't assume we know how `cElementTree` has changed. It is likely the internals of `cElementTree` also deprecated methods similarly to `ElementTree`.

We just followed the official Python recommendations to move away from deprecated methods.

When we have time, we'll do a complete rewrite to remove the deprecated `cElementTree` from [`xlrdinc`](https://github.com/inclusive-dev1/xlrdinc).

**Comment by cjw296** [comment] 2019-05-22 11:35
What's the actual problem here? If it's DeprecationWarnings or some variant of them, just ignore them.
Can someone please give me a succinct explanation of what problems any of this is causing?

**Comment by tutordelphia** [comment] 2019-05-22 13:25
@cjw296 Thank you for responding and cleaning up the open issues! For business use, a lot of legacy formats (like `xls`) are slow to go away (when dealing with historical data).

This is not much of an issue, except that it causes extra noise when running tests. I guess there is just an expectation that the squeaky wheel gets the grease.

**Comment by cjw296** [comment] 2019-05-22 13:32
I have a major bugbear with deprecation warnings because they waste time like this and cause entities like @inclusive-dev1, whoever they are, to start doing insane things.

Just add a warnfilter for them and come back when something actually breaks.

@inclusive-dev1, whoever you, after making such a fucking mess of community interactions, how about dropping me a mail before you try and steal the projects on pypi, eh?

**Comment by dwt** [comment] 2019-05-22 13:46
@cjw296 I can understand you are upset - but this project did look like the maintainer has moved on to greener pastures for months with no response (I mean it's an open source project, so it's fine it takes the maintainer some time to get around answering, but this was really long).

Given that, I think it's great people care enough that they are willing to spend the time to take over maintenance of a project.

**Comment by dwt** [comment] 2019-05-22 13:47
If possible I would advise that it could be a good idea to add more maintainers to this project.

**Comment by cjw296** [comment] 2019-05-22 14:39
@dwt - are you affiliated with @inclusive-dev1? I'd really like to speak to whatever that is.
It's the way they went about it, not once did anyone actually email me. 

I had unwatched this tracker as yes, I do have other things to be working on, and I'm still trying to see some substantive issue that would warrant the behaviour exhibited.

**Comment by dwt** [comment] 2019-05-22 15:59
I am not - but I would encourage you to maybe send him an email or give him a call?

If you did unwatch this tracker - why are you surprised people thought that this project was unmaintained / dead?

That being said - what is the actual problem you have with @inclusive-dev1? He created a private fork as they need it internally anyway and want it installed, then he announced that he would be willing to take up maintainership and was announcing so publicly. He did get advised to try to contact you off the open bug trackers and maybe went a bit too quick with trying to take over the project on pypi - but if I remember it right, proving that there is no way to contact the original maintainer is part of that process, which is the actual idea of it anyway.

For the future: please don't unwatch the bug trackers of projects you are the maintainer  without announcing that in the readme and maybe how to contact you if somebody is willing to help you maintain it.

**Comment by inclusive-dev1** [comment] 2019-05-22 17:25
> What's the actual problem here? If it's DeprecationWarnings or some variant of them, just ignore them.
> Can someone please give me a succinct explanation of what problems any of this is causing?

The problem was described in rather full form at [my comment above](https://github.com/python-excel/xlrd/issues/315#issuecomment-493759998).

But succinctly, `xlrd` is coded on deprecated Python functions, and should keep pace with Python to avoid being bitten by surprise in future (eg. when *deprecation* becomes outright *dropped*). More seriously, the part of the codes we're discussing is now loaded with unnecessary codes. Unnecessary codes can create surprising and unanticipated problems; at the minimum, they represent codes that are by now *unaccounted for*.

**Comment by cjw296** [comment] 2019-05-22 17:26
Please don't try and tell me what to do on a project unless you're going to offer significant funding to cover my time on it.

**Comment by cjw296** [comment] 2019-05-22 17:27
Ah, an @inclusive-dev1 magically appears. Drop me an email, let's start a discussion, but bearing in mind you're starting from a position where you've made a really really terrible first impression.

**Comment by inclusive-dev1** [comment] 2019-05-22 17:27
> Given that, I think it's great people care enough that they are willing to spend the time to take over maintenance of a project.

@dwt We actually care enough that we were holding off publicly pointing to `xlrdinc` until someone came up with a better name (if forking a speedier development), or the maintainers came in to chime in.

**Comment by inclusive-dev1** [comment] 2019-05-22 17:35
> Please don't try and tell me what to do on a project unless you're going to offer significant funding to cover my time on it.

@cjw296 Oh. Ok, I think I get where you're coming from. I didn't tell u what to do with the project. Was just objectively answering your question about *what, succinctly, is the problem here*.

Look, people need money to live. If it's a money issue, u get zero arguments from me. FYI, I'm really not @dwt .

Whether or not you argue against my open-source comment (peer review, succinct and frank analysis, etc), I'm really on your side now. All it took for me was to read that it's a *funding issue*. We have employers closing our open-source projects all the time, and then paying us too little to sacrifice our open-source rep.

Glad you're back on board. But I'm again offering to take over this *under the maintainers' names*, and also as per [our advertised intention here](https://github.com/pypa/warehouse/issues/5895#issue-446882704), to study all dependencies and keep `xlrd` in pace with these dependencies. (We've studied `defusedxml`, and would contribute there to if need be.)

**Comment by cjw296** [comment] 2019-05-22 17:36
What part of "drop me an email" did you not understand?

**Closed** 2019-05-22 17:36 UTC
